"""add_coupon_code_to_cart

Revision ID: df564333ceb8
Revises: dfae5e106d0c
Create Date: 2026-05-14 22:24:07.560950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df564333ceb8'
down_revision: Union[str, None] = 'dfae5e106d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('coupon_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'coupon_code')
    # ### end Alembic commands ###
